# -*- coding: utf-8 -*-
"""github code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EveBrVXOCIlWIDsd2zMk__LnFoeNAdQD
"""

num = int(input("enter your number to check "))
isdivisible = False ;

i = 2 ;
while i < num :
  if num % i ==0 :
     isdivisible = True ;
     print("{} is divisible by {}".format(num,i))
     break ;

     i += 1
if isdivisible == False  :
  print("{} is a prime number".format(num))
else :
  print("{} is not a prime number".format(num))